#!/bin/bash

# Credits: https://hub.docker.com/u/justfalter/

cat > /var/lib/postgresql/data/pg_hba.conf <<EOS
# Generated by fix-acl.sh
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust

# Allow remote connections only from Docker's range. Password is required.
host    all             all             172.17.0.0/16           md5 
EOS
